version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - PORT=3000
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - '.env.demo:/srv/.env'

  # Redis Cluster (localhost)
  redis-cluster-localhost-access:
    image: grokzen/redis-cluster:6.2.1
    environment:
      IP: '0.0.0.0'
      INITIAL_PORT: 7000
      MASTERS: 3
      SLAVES_PER_MASTER: 1
    ports:
      ## INITIAL_PORT ~ (INITIAL_PORT + MASTERS * (1 + SLAVES_PER_MASTER) -1)
      - '${REDIS_CLUSTER_PORT_RANGE:-7000-7005}:7000-7005'
