version: '3.9'

services:
  # MongoDB
  mongodb:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nestjs_starter
    ports:
      - '${MONGODB_PORT:-27017}:27017'

  # PostgreSQL
  postgres:
    image: postgres:14
    environment:
      - 'POSTGRES_USER=nestjs'
      - 'POSTGRES_PASSWORD=example'
      - 'POSTGRES_DB=nestjs'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    ports:
      - '${PG_PORT:-5432}:5432'
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data

  # Redis
  redis-standalone:
    image: redis:6.2-alpine
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - './.docker/redis/data:/data'

  redis-cluster:
    image: grokzen/redis-cluster:6.2.1
    environment:
      INITIAL_PORT: 7000
      MASTERS: 3
      SLAVES_PER_MASTER: 1

  # RabbitMQ
  rabbitmq:
    image: 'rabbitmq:3.9.11-management'
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=example
    ports:
      - '${RABBITMQ_NODE_HOST_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT:-15672}:15672'
